# Generated by Django 6.0.3 on 2026-07-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='ai_prompt',
        ),
        migrations.RemoveField(
            model_name='page',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_homepage',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_breadcrumb',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_title',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='config',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='section_subtitle',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='section_title',
        ),
    ]
