# Generated by Django 6.0.3 on 2026-07-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_page_ai_prompt_remove_page_classes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='pagesection',
            old_name='image_asset',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='config',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='page',
            name='custom_js',
        ),
    ]
