# Generated by Django 6.0.3 on 2026-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_featured_image_page_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='excluded_posts',
            field=models.JSONField(blank=True, default=list, help_text='IDs of child posts unchecked by an admin.'),
        ),
    ]
